4th task done
js-tasks-ru/vue-20231109_oleg-larionov pull request #5
Opened 2023-12-01 12:12 UTC by GreddyFox

2023-12-01 12:13 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-12-01 12:18 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2023-12-09 14:16 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @ShGKme

2023-12-13 02:11 UTC, ShGKme requested changes
Требуются небольшие исправления в `04-vue-cli/02-TheToaster`, остальные задачи приняты.

2023-12-13 02:11 UTC, ShGKme commented on 04-vue-cli/02-TheToaster/components/UiToast.vue
> +        }
С событием не нужно отдавать идентификатор `this.config.index`, который этому компоненту в целом не нужен. Его родитель итак знает, у какого тоста порождается событие `expired`. Он знает этот индекс, который сейчас получается вместе с событием, потому что он сам же ему его отдаёт. Сейчас индекс просто получается от родителя и отправляется ему же обратно.

При этом не может возникнуть ситуации, когда один тост будет сообщать об удалении какого-то другого тоста с другим индексом. Лучше не передавать лишних данных в событиях

2023-12-13 02:11 UTC, ShGKme commented on 04-vue-cli/02-TheToaster/components/TheToaster.vue
> +    <UiToast v-for="toastConfig in toasts" :key="toastConfig" :config="toastConfig" @expired="handleDeletion" />
Здесь `TheToaster` косвенно передаёт в `UiToast` индекс через `:config="toastConfig"`, а потом его же ловит и использует в `@expired="handleDeletion"`. Вместо отправки индекса по кругу можно явно передать его сразу: `@expired="handleDeletion(toastConfig.index)"`.

2023-12-13 02:11 UTC, ShGKme commented on 04-vue-cli/02-TheToaster/components/TheToaster.vue
> +      );
Индекс (`this.toasts.length`) - не очень удачный вариант для идентификатора. В таком варианте он работает, но если тосты смогут удаляться произвольно (например, кнопкой закрытия), то получится дублирование индекса, который используется как уникальный идентификатор.

2023-12-13 02:11 UTC, ShGKme commented on 04-vue-cli/02-TheToaster/components/TheToaster.vue
> +      );
Сейчас в `UiToast` передаётся `type` из которого он определяет класс в зависимости от типа тоста. Будет удобно, если иконку компонент также будет определять сам.

2023-12-13 02:11 UTC, ShGKme commented on 04-vue-cli/02-TheToaster/components/UiToast.vue
> +    <div class="toast toast_success" :class="{ ['toast toast_error']: config.type === 'error' }">
Здесь всегда выводится класс для `success` тоста, и лишь `toast_error` выводится по условию. При этом для `error` тоста общий класс тоста `toast` выводится всегда.

2023-12-13 02:11 UTC, ShGKme commented on 04-vue-cli/02-TheToaster/components/UiToast.vue
> +        }
Также это событие не указано в `emits`

2023-12-13 02:11 UTC, ShGKme commented on 04-vue-cli/02-TheToaster/components/UiToast.vue
> +    },
Обычно вместо одного параметра объекта `config` удобнее добавлять компоненту отдельные простые параметры для сообщения, типа и т.д.

2023-12-14 11:43 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2023-12-14 22:40 UTC, ShGKme approved these changes

2023-12-14 22:42 UTC, merged